### PR TITLE
Suggest new layer names based on common pattern

### PR DESCRIPTION
**Pull request by porada**
**▶️ [See the changes in action](https://imgur.com/a/YPMH7)**

Added a couple lines of code for suggesting a layer name based on selection. It’s something I find myself doing manually over and over again. The choice of `%n` may seem a little opinionated, but it’s possible that others will find it useful, too.

The plugin only handles prefixes at the moment, but can be extended to suffixes and more general patterns in the future, too.

Let me know what you think.

### CODE REVIEW

**Comment by porada** [comment]
The original code style is a little inconsisted, so please point out if I should tweak the additions. 👌

**Comment by rodi01** [comment]
This is a good idea!
I'm about to release a completely rewrite of the plugin, once I do that, I will get your changes in. 

Thanks!

**Comment by porada** [comment]
Ouch, I didn’t dig deep enough to see you were close to shipping a new version—I would have made a pull request to the new codebase.

If you need anything from me, just ping me. I’m happy to help. 👍

**Comment by rodi01** [comment]
Thanks @porada!

Feel free to check out the v3 branch. I'm working on documentation right now, when I think it's done I find something else to fix or do. 😕

**Comment by rodi01** [comment]
Added something similar to the last release

**Comment by porada** [comment]
Awesome. Thanks for letting me know.

**Pull request closed without merging**
